# Site settings
title: "Nadine Ramsden"
#email: contact@nadineramsden.ca
#description: ""
#url: "http://nadineramsden.ca" # the base hostname & protocol
github_username: nadineramsden
#logo: /images/logo/ram_logo.png
# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
# gems:
#   - jekyll-redirect-from
#   - jekyll-sitemap
#   - jekyll-seo-tag
#   - jekyll-paginate
#   - jekyll-gist

# exclude:
